### ISSUE TITLE
alignment not good.

### ISSUE THREAD

**Issue by YiChenCityU** [mpkuse/edge_alignment#1]
Hi, Manohar. 
Thanks for your open source code. I am also interested in edge_alignment. I have run your edge_alignment code on TUM RGBD dataset. But the result was not good enough. Even with 100 iteration the cost still very high. Do you have some data that I can try? or some thing I need to pay attention?

Thanks very much.

**Comment by mpkuse** [comment]
Hi,
Thanks for your interest in our work. This repo was an attempt for me to have a standalone
implementation of edge alignment. This is not ready yet (i didn't find time to complete it). 
It has some bugs that need fixing. In particular, this uses google's ceres solver and the issue is in defining a grid-based cost function. Contributions welcome!

I believe, Yongyen (https://github.com/ygling2008/direct_edge_imu) in his repo had
fixed it and is usable. I can see you have raised the issue there. You are better off trying to
run his code. 

You may look at https://kusemanohar.wordpress.com/2015/09/14/icra2015-submission/
for more resources on this project. 

If you are keen on using this, I suggest you implement the gradient decent yourself for this. Once you have a point cloud it is really not that hard. I can try and implement a shortcode but cannot guarantee. 

Good luck!

**Comment by YiChenCityU** [comment]
So great. Thanks very much for your instruction. I will read your paper  thoroughly.
